name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setting up build version
        run: |
          $version = "1.0.{0:#}" -f $($Env:GITHUB_RUN_NUMBER)
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          
      - name: Setup build version
        run: dotnet build --configuration Release --output ${{env.DOTNET_ROOT}}/Package
        
      - name: Build with dotnet
        run: dotnet build --configuration Release --output ${{env.DOTNET_ROOT}}/Package

      - name: Publish NuGet Package
        run: dotnet nuget push ${{env.DOTNET_ROOT}}/Package/*.nupkg --api-key ${{ secrets.NUGET_KEY }}
        
